### ISSUE TITLE
I can't find where I am supposed to see the alternative login options

### ISSUE THREAD

**Issue by sunnysideup** [sandervanscheepen/silverstripe-cms-userswitcher#4]

**Comment by sunnysideup** [comment]
Hoi Sander,

I was wondering where I should see the option to switch to another user. I can't see it anywhere. 

BTW, great module. I just made two random pull requests for removing indents. Feel free to ignore. Keen to know if you have these indents for a reason.

**Comment by sandervanscheepen** [comment]
Hello Sunny Side Up,

thank you for your input and kind words. The newest release has some screenshots in the README and more explanation about these options only being available to users with admin permissions. Let me know if some things are still unclear.

**Comment by sunnysideup** [comment]
This is what I see when I am logged in:
![image](https://user-images.githubusercontent.com/167154/189994428-aecec30d-3ea8-4eb4-a688-bb181c8680ba.png)

**Comment by sandervanscheepen** [comment]
The dropdown with users is only shown when the feature is active for both yourself and at least one other Member. 

In the CMS first go to 'Security' and lookup your own Member record. At the bottom of that page enable both checkmarks. Then go back to the gridfield of 'Security', select another Member and also enable the checkbox(es) for that user. Now refresh the browser window. Now there should be a dropdownmenu in the top left of the screen.

**Comment by sunnysideup** [comment]
Slow reply, but this now works a treat!
